### ISSUE TITLE
expand build and running instructions for different platforms

### ISSUE THREAD

**Issue by samypr100** [trinity-xai/Trinity#13]
Current description is very minimal.

**Comment by czp13** [comment]
Mac build/run instruction could be a good improvement, right? 
(As I have a Mac I could help theoretically in that, if I can make the build succeed :))

**Comment by czp13** [comment]
Ok, I was able to build, and run it with the scripts, but I have no idea how to debug it for example :)

**Comment by czp13** [comment]
I tried to create a PR with improved instructions but I was not able to do it :(
If any of you could give me create PR permission it would be much appreciated! 🙇 

```
    ~/Pr/Trinity/scripts    add_mac_mvn_build_steps      git push --set-upstream origin add_mac_mvn_build_steps                             128 ✘  base   11:34:35 PM 
ERROR: Permission to Birdasaur/Trinity.git denied to czp13.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

**Comment by samypr100** [comment]
@czp13 Thanks for your interest in contributing. Feel free to fork the repo and submit a PR that way, we can than review. Thanks!

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by Birdasaur** [comment]
@czp13 Hey Peter it was really great meeting you at Devoxx last week and I'm glad to see you are still interested in Trinity.
Once you make a fork, let us know if you have any issues with submitting a PR from your fork. We'll be happy to work with you.

**Comment by czp13** [comment]
Hey @samypr100  and @Birdasaur,

(I will use GitHub names as you did not share other info, so I will stick to it ;))

It was nice to meet with both of you as well last week at the conference. 
It was a very memorable presentation and meeting 👏 🙇  
I am a bit sad that I could not join the Best Of (JavaFx) Friends event :D

 Also, I think let us drop the LinkedIn conversation, easier to do here, as it is more in context. 
(I plan to push bit your presentation through LinkedIn if you do not mind as it shall have more views really)

**Project:**
I may need some more info as I am stuck now how to debug the project (Apple M1), but maybe it is just my environment (build and script execution works, but that is not optimal workflow for developing and bughunting :S), 
getting these, not nice errors ATM:

```
Entering Trinity main...
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/pczuczor/.openjfx/cache/20.0.2+3/x86_64/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/pczuczor/.openjfx/cache/20.0.2+3/x86_64/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:1979)
	at javafx.graphics@20.0.2/com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at javafx.graphics@20.0.2/com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at javafx.graphics@20.0.2/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at javafx.graphics@20.0.2/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at javafx.graphics@20.0.2/com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at javafx.graphics@20.0.2/com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:383)
	at java.base/java.lang.Class.forName(Class.java:376)
	at javafx.graphics@20.0.2/com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:833)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/pczuczor/.openjfx/cache/20.0.2+3/x86_64/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/pczuczor/.openjfx/cache/20.0.2+3/x86_64/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:1979)
	at javafx.graphics@20.0.2/com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at javafx.graphics@20.0.2/com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at javafx.graphics@20.0.2/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at javafx.graphics@20.0.2/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at javafx.graphics@20.0.2/com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:43)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at javafx.graphics@20.0.2/com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:383)
	at java.base/java.lang.Class.forName(Class.java:376)
	at javafx.graphics@20.0.2/com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:833)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:263)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at javafx.graphics@20.0.2/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:275)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:833)

Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found

Execution failed for task ':TrinityMain.main()'.
> Process 'command '/Users/pczuczor/Library/Java/JavaVirtualMachines/openjdk-18.0.2-1/Contents/Home/bin/java'' finished with non-zero exit value 1
```

No worries I will play around (maybe my JDK version, etc) when I have time, not working to Vaadin.

**Comment by czp13** [comment]
Also Forking works, I was just in a lucky situation that I was a contributor to opensource projects from the inside so was easy to review, create PR-s, etc, but I will see the other side now :D

**Comment by czp13** [comment]
Ok, I am able to debug it finally, yeah.
(Specific Java and Gradle command, params were needed, but the config is working nicely for M1 as well, minimum setup needed, good job!):

![image](https://github.com/Birdasaur/Trinity/assets/61667986/21405d21-408e-4532-9311-9c84d76fe25e)

**Comment by Birdasaur** [comment]
Nice work!
