### ISSUE TITLE
Image Based Hyperbolic Navigator

### ISSUE THREAD

**Issue by Birdasaur** [trinity-xai/Trinity#69]
Build UI tool for ingesting and rapidly navigating imagery from a collection based on human understandable axes.
Tool should provide the user with multiple rendered axes by which they can slide or hop through the latent space, either via a target reticule or polar angle system.
The Image/Content associated with the embedding vector for the current location in the coordinate space should be displayed in a portrait view. 
This update should occur instantly to allow the user to gain a "sense of something" from navigating the latent space.

**Comment by Birdasaur** [comment]
@samypr100 
While in the process of building the GUI controls for the new HTTP service I am encountering errors when httpx.post() ing messages to Trinity:

`Traceback (most recent call last):
  File "C:\dev\trinity\trippiny.py", line 10, in <module>
    r = httpx.post("http://10.134.9.239:8080", json=fileJson) #json.dumps(fileJson)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phillsm1\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_api.py", line 331, in post
    return request(
           ^^^^^^^^
  File "C:\Users\phillsm1\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_api.py", line 118, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "C:\Users\phillsm1\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 837, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phillsm1\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phillsm1\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phillsm1\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phillsm1\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phillsm1\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_transports\default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\phillsm1\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\phillsm1\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_transports\default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError: [WinError 10053] An established connection was aborted by the software in your host machine`

**Comment by Birdasaur** [comment]
@samypr100  
This does not occur on the first post() sent to Trinity. The first post is fine.
It is all subsequent posts to Trinity. The only workaround is to restart Trinity. 
This makes me believe that we are missing something in how we are responding or flushing the channel.
